package main

const COMM_SPEED_INC = 0
const COMM_SPEED_DEC = 1
const COMM_TOGGLE = 2
const COMM_SINGLE_CHARACTER = 3
const COMM_RESIZE = 4
const COMM_CONFIRM = 5
const COMM_BACKSPACE = 6
const COMM_SENTENCE_BACKWARD = 7
const COMM_SENTENCE_FORWARD = 8

const COMM_DIGIT_0 = 0xff
const COMM_DIGIT_9 = COMM_DIGIT_0 + 9
