package main

const (
	COMM_SPEED_INC = iota
	COMM_SPEED_DEC
	COMM_TOGGLE
	COMM_SINGLE_CHARACTER
	COMM_RESIZE
	COMM_CONFIRM
	COMM_BACKSPACE
	COMM_SENTENCE_BACKWARD
	COMM_SENTENCE_FORWARD
)

const COMM_DIGIT_0 = 0xff
const COMM_DIGIT_9 = COMM_DIGIT_0 + 9
